### ISSUE TITLE
Hi I'm having trouble using this to check a display

### ISSUE THREAD

**Issue by karava** [insanoid/iPhone-6-Store-Reserve-Monitor#17]
Hi there,

Thanks for sharing this code, it's amazing.
I was wondering it would be easy to alter this to check for the LG Ultrafine 4k monitor, in Australia (https://www.apple.com/au/shop/product/HMUA2X/A/lg-ultrafine-4k-display).

I tried the following config but it didn't work:
{
  "country_code": "au",
  "models": "HMUA2X",
  "zip_code": "3000"
}

Please provide some tips if you can!
Happy to help you maintain or extend this program in the future.

Regards,
Kishan

**Comment by nonissue** [comment]
Not sure if you still care about this, I think it's because non-apple products don't use the same API this relies on (`product-locator-meta`). You can search for individual third party products like this though:

`https://www.apple.com/au/shop/retail/pickup-message?parts.0=HMUB2X%2FA&store=R238`

Where R238 is the store number (I just picked sydney as an example).
You can find apple store numbers here: https://applestorefronts.appspot.com

A quick glance at the initial readme, and I think you could search for products with the following config: 

```
{
  "country_code": "au",
  "models": ["HMUA2X/A"],
  "stores": ["R238"]
}
```

Haven't tested it though!

**Comment by karava** [comment]
Thanks very much for responding!
I have all the apple products I need for the moment, put will keep this in
mind next time, I'm after a scarce product!

Kind regards,
- Kishan
